"""
Watsonx direct Q&A tool – lets the agent ask IBM watsonx Granite any
free-form research question and get a grounded, scholarly answer.
"""
from __future__ import annotations

import os
from typing import Optional

import requests
from pydantic import BaseModel, Field

from ibm_watsonx_orchestrate.agent_builder.tools import tool, ToolPermission


# ─── Schemas ────────────────────────────────────────────────────────────────

class WatsonxQueryInput(BaseModel):
    question: str = Field(
        ..., description="Research question or prompt to send to watsonx Granite"
    )
    context: Optional[str] = Field(
        None, description="Optional background context to include with the question"
    )
    max_tokens: Optional[int] = Field(
        default=600, description="Maximum tokens for the response (100-1500)"
    )


class WatsonxQueryOutput(BaseModel):
    question: str = Field(description="Original question asked")
    answer: str = Field(description="Answer generated by IBM watsonx Granite")
    model: str = Field(description="Model used for generation")
    error: Optional[str] = Field(None, description="Error message if query failed")


# ─── Constants ───────────────────────────────────────────────────────────────

WATSONX_URL = "https://us-south.ml.cloud.ibm.com/ml/v1/text/generation?version=2023-05-29"
WATSONX_MODEL = "ibm/granite-4-h-small"
WATSONX_PROJECT_ID = "cbf265ef-b635-441e-9fb3-600fe79d80af"


# ─── Helpers ─────────────────────────────────────────────────────────────────

def _get_iam_token(api_key: str) -> str:
    resp = requests.post(
        "https://iam.cloud.ibm.com/identity/token",
        data={"grant_type": "urn:ibm:params:oauth:grant-type:apikey", "apikey": api_key},
        headers={"Content-Type": "application/x-www-form-urlencoded"},
        timeout=15,
    )
    resp.raise_for_status()
    return resp.json()["access_token"]


def _call_watsonx(prompt: str, api_key: str, max_new_tokens: int) -> str:
    token = _get_iam_token(api_key)
    payload = {
        "model_id": WATSONX_MODEL,
        "project_id": WATSONX_PROJECT_ID,
        "input": prompt,
        "parameters": {
            "decoding_method": "greedy",
            "max_new_tokens": min(max(max_new_tokens, 100), 1500),
            "repetition_penalty": 1.05,
        },
    }
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    resp = requests.post(WATSONX_URL, json=payload, headers=headers, timeout=60)
    resp.raise_for_status()
    results = resp.json().get("results", [])
    return results[0].get("generated_text", "").strip() if results else ""


# ─── Tool ────────────────────────────────────────────────────────────────────

@tool(permission=ToolPermission.READ_ONLY)
def query_watsonx(input: WatsonxQueryInput) -> WatsonxQueryOutput:
    """
    Send a research question directly to IBM watsonx Granite and receive a scholarly answer.

    Use this tool when the user asks a factual or analytical research question
    that requires general knowledge, explanation, or analysis rather than a
    database search.

    Args:
        input (WatsonxQueryInput): Research question, optional context, and token limit.

    Returns:
        WatsonxQueryOutput: The generated answer and model metadata.
    """
    api_key = os.environ.get("WATSONX_API_KEY", "")
    if not api_key:
        return WatsonxQueryOutput(
            question=input.question,
            answer="",
            model=WATSONX_MODEL,
            error="WATSONX_API_KEY environment variable is not set.",
        )

    context_block = f"\nContext:\n{input.context}\n" if input.context else ""
    prompt = (
        f"You are an expert scientific research assistant. "
        f"Answer the following question clearly and accurately in an academic style.{context_block}\n"
        f"Question: {input.question}\n\nAnswer:"
    )

    try:
        answer = _call_watsonx(prompt, api_key, input.max_tokens or 600)
        return WatsonxQueryOutput(
            question=input.question,
            answer=answer,
            model=WATSONX_MODEL,
        )
    except Exception as exc:
        return WatsonxQueryOutput(
            question=input.question,
            answer="",
            model=WATSONX_MODEL,
            error=str(exc),
        )
